version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  # We'll add database service here later when we implement persistence
